FROM debian:buster

# installer MariaDB
RUN apt-get update -y
RUN apt upgrade -y
RUN apt-get install -y mariadb-server
# droits pour la database + exec sript
RUN chmod +x /usr/local/bin/database.sh
RUN /usr/local/bin/database.sh

# installer MySQL
COPY conf/50-server.cnf	/etc/mysql/mariadb.conf.d/50-server.cnf
COPY tools/database.sh /usr/local/bin/database.sh
