FROM debian:buster

# installer MariaDB
RUN apt-get update -y
RUN apt upgrade -y
RUN apt-get install mariadb-server -y

# installer MySQL
COPY conf/50-server.cnf	/etc/mysql/mariadb.conf.d/50-server.cnf
