# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mprigent <mprigent@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/08/09 23:36:32 by mprigent          #+#    #+#              #
#    Updated: 2022/08/21 21:34:17 by mprigent         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# installer MariaDB
RUN apt-get update -y
RUN apt upgrade -y
RUN apt-get install -y mariadb-server
# droits pour la database + exec sript
RUN chmod +x /usr/local/bin/database.sh
RUN /usr/local/bin/database.sh

# installer MySQL
COPY conf/50-server.cnf	/etc/mysql/mariadb.conf.d/50-server.cnf
COPY tools/database.sh /usr/local/bin/database.sh

ENTRYPOINT ["bash", "auto_config.sh"]

