# OS sous lequel doit tourner la VM
FROM	debian:buster

# verifie les MAJ, installe Nginx, vim et curl
RUN	apt-get update
RUN	apt-get install -y nginx
RUN	apt install -y vim
RUN	apt install -y curl
# crée un dossier pour stocker certificat et connexion sécurisée
RUN mkdir -p /etc/nginx/ssl
# télécharge OpenSSL (outil principal de gestion/création de certificats SSL)
RUN apt install -y OpenSSL
# req crée et traite principalement des demandes de certificats au format PKCS#10, -x509 pour préciser le type du certificat, -nodes = clé privée sans mot de passe, -subj permet de préremplir le prompt qui requiert certaines infos 
RUN	openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/C=FR/ST=IDF/L=Paris/O=42/OU=42/CN=mprigent.42.fr/UID=mprigent"
# crée un dossier qui permettra de stocker les fichiers de config nginx
RUN mkdir -p /var/run/nginx
# droits sur ce dont on a besoin (root principal et utilisateur principal)
RUN chmod 755 /var/www/html
RUN chown -R www-data:www-data /var/www/html

# fichier à copier depuis repertoire nginx installé au début -> endroit ou le copier dans la VM
COPY conf/nginx.conf /etc/nginx/nginx.conf

# informe docker que le conteneur écoute sur le port réseau spécifié (443 permet l'accès par https)
EXPOSE	443

# Lance nginx en premier plan et non en background pour que le container ne se stop pas
CMD	[ "nginx", "-g", "daemon off;" ]
