# OS sous lequel doit tourner la VM
FROM	debian:buster

# verifie les MAJ, installe Nginx, vim et curl
RUN		apt-get update
RUN		apt-get install nginx -y
RUN		apt install vim -y
RUN		apt install curl -y
# crée un dossier pour stocker certificat et connexion sécurisée
RUN 	mkdir -p /etc/nginx/ssl
# télécharge OpenSSL (outil principal de gestion/création de certificats SSL)
RUN 	apt install OpenSSL -y
# req crée et traite principalement des demandes de certificats au format PKCS#10, -x509 pour préciser le type du certificat, -nodes = clé privée sans mot de passe,  
RUN		openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key

# fichier à copier depuis repertoire -> endroit ou le copier dans la VM
#  COPY	tools/nginx.conf /etc/nginx/http.d/default.conf

# # informe docker que le conteneur écoute sur le port réseau spécifié (443 permet l'accèa par https)
# EXPOSE	443

# # Lance nginx en premier plan et non en background pour que le container ne se stop pas
# CMD	[ "nginx", "-g", "daemon off;" ]
